AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'eb_flask_api

  Notify Slack when an issue is detected by Elastic Beanstalk

  '
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        URL: https://hooks.slack.com/services/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
Resources:
  NotifySlackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lambda-eb-notify-slack/952f197d1ae7be83ff963316698d22c1
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        EBProblem:
          Type: Api
          Properties:
            Path: /notify_slack
            Method: GET
Outputs:
  EBProblemApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/notify_slack/
  NotifySlackFunction:
    Description: Notify Slack Lambda Function ARN
    Value:
      Fn::GetAtt:
      - NotifySlackFunction
      - Arn
  NotifySlackFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - NotifySlackFunctionRole
      - Arn
